"""remove season from series

Revision ID: e6ab99072ec8
Revises: 
Create Date: 2026-04-10 10:31:06.830667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ab99072ec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_season'))
        batch_op.drop_column('season')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.VARCHAR(length=10), nullable=False))
        batch_op.create_index(batch_op.f('ix_series_season'), ['season'], unique=False)

    # ### end Alembic commands ###
